################################################################################
#                                                                              #
# ZeBu (R) - Copyright (c) 2003 - 2017 by Synopsys, Inc                        #
# -------------------------------------------------------                      #
#                                                                              #
#   Sets variables for zDB                                                     #
#   This file has been generated by zTopBuild.                                 #
#                                                                              #
################################################################################

set build_zcore_dir_list [list {work.Part_0} ]
