# Generated by zTopBuild
#
set nb_modules 1

source $env(ZEBU_ROOT)/etc/ztoppartitioning/zTopPartitioning.tcl

# zdelay ratio : 0.70
set_primitive_resource fd* REG      1.43
set_primitive_resource ld* REG      1.43

# qiwc
set_module_resource zfwc_qiwc* REG 0.1
set_module_resource zfwc_qiwc* LUT 0.3
set_module_resource zfwc_qiwc* LUT6 0.3

set fpga_num_lut     610800
set fpga_num_reg     537504
set fpga_num_ram     645
set fpga_num_dsp     1080
set fpga_num_ramlut  137920
set fpga_num_lut6    244320
set fpga_num_fwcip_bits 65138
set fpga_num_qiwc_bits 209715
set fpga_num_read_port_ips 256
set fpga_num_read_port_bits 8192
set fpga_num_write_port_ips 256
set fpga_num_write_port_bits 8192
set fpga_num_zc_trace_bit 65536
set fpga_num_fw_resources 47721858
set fpga_num_zprd 8000
set fpga_num_zcei_mess_in 486
set fpga_num_zcei_mess_out 486

set_nb_bits_per_fwc_ip 384

# default min resources
defcore_resource -min LUT 610800
defcore_resource -min REG 537504
defcore_resource -min RAM 645
defcore_resource -min DSP 1080
defcore_resource -min RAMLUT 137920
defcore_resource -min LUT6 244320
defcore_resource -min FWC_IP_NUM 793
defcore_resource -min FWC_IP_BITS 65138
defcore_resource -min QIWC_IP_BITS 209715
defcore_resource -min READ_PORT_IPS 256
defcore_resource -min READ_PORT_BITS 8192
defcore_resource -min WRITE_PORT_IPS 256
defcore_resource -min WRITE_PORT_BITS 8192
defcore_resource -min ZC_TRACE_BIT 65536
defcore_resource -min ZCEI_MESSAGE_INPUT 486
defcore_resource -min ZCEI_MESSAGE_OUTPUT 486
defcore_resource -min FW_RESOURCES 47721858
defcore_resource -min ZPRD_BB 0
defcore_resource -min ZRM_SLOTS 0
defcore_resource -min ZRM_PORTS 0
defcore_resource -min ZFORCE 8000
defcore_resource -min ZVIEW 0

# default max resources
set max_fpga_num 9
defcore_resource -max LUT 5497200
defcore_resource -max REG 4837536
defcore_resource -max RAM 5805
defcore_resource -max DSP 9720
defcore_resource -max RAMLUT 1241280
defcore_resource -max LUT6 2198880
defcore_resource -max FWC_IP_NUM 7137
defcore_resource -max FWC_IP_BITS 586242
defcore_resource -max QIWC_IP_BITS 1887435
defcore_resource -max READ_PORT_IPS 2304
defcore_resource -max READ_PORT_BITS 73728
defcore_resource -max WRITE_PORT_IPS 2304
defcore_resource -max WRITE_PORT_BITS 73728
defcore_resource -max ZC_TRACE_BIT 589824
defcore_resource -max ZCEI_MESSAGE_INPUT 0
defcore_resource -max ZCEI_MESSAGE_OUTPUT 0
defcore_resource -max FW_RESOURCES 429496722
defcore_resource -max ZPRD_BB 0
defcore_resource -max ZRM_SLOTS 147456
defcore_resource -max ZRM_PORTS 80
defcore_resource -max ZFORCE 72000
defcore_resource -max ZVIEW 900000
# default global resources
set global_fpga_num 9
defcore_resource -global LUT 5497200
defcore_resource -global REG 4837536
defcore_resource -global RAM 5805
defcore_resource -global DSP 9720
defcore_resource -global RAMLUT 1241280
defcore_resource -global LUT6 2198880
defcore_resource -global FWC_IP_NUM 7137
defcore_resource -global FWC_IP_BITS 586242
defcore_resource -global QIWC_IP_BITS 1887435
defcore_resource -global READ_PORT_IPS 2304
defcore_resource -global READ_PORT_BITS 73728
defcore_resource -global WRITE_PORT_IPS 2304
defcore_resource -global WRITE_PORT_BITS 73728
defcore_resource -global ZC_TRACE_BIT 589824
defcore_resource -global ZCEI_MESSAGE_INPUT 486
defcore_resource -global ZCEI_MESSAGE_OUTPUT 486
defcore_resource -global FW_RESOURCES 2147483610
defcore_resource -global ZPRD_BB 8000
defcore_resource -global ZRM_SLOTS 147456
defcore_resource -global ZRM_PORTS 80
defcore_resource -global ZFORCE 72000
defcore_resource -global ZVIEW 900000

# false paths

set_max_blocks 20000

set_max_parts 1

set_lut_weighting 1 0.0

save_defmapping zTopBuild_AC_defcoremap.tcl

save_defmapping -defcore zTopBuild_AP_defcore.tcl

save_defmapping -defcore zTopBuild_AP_incremental_defcore.tcl

save_defmapping zTopBuild_AC_incremental_defcoremap.tcl -incremental -block zTopBuild_AC_incremental_interco.txt

source {tools/zTopPartitioning/constraints.tcl}

# Defgroup commands

set_max_zcei_parts 0
set_max_rtlclk_parts 1
set_arch -product zse -fpga V7
defZRMBank -loc U0_M0 -depth 134217728 -width 512 -ports 8 -full_loc U0_M0_F8
defZRMBank -loc U0_M0 -depth 134217728 -width 512 -ports 8 -full_loc U0_M0_F8
defZRMBank -loc U0_M0 -depth 33554432 -width 64 -ports 8 -full_loc U0_M0_F7
defZRMBank -loc U0_M0 -depth 33554432 -width 64 -ports 8 -full_loc U0_M0_F7
defZRMBank -loc U0_M0 -depth 33554432 -width 64 -ports 8 -full_loc U0_M0_F6
defZRMBank -loc U0_M0 -depth 33554432 -width 64 -ports 8 -full_loc U0_M0_F6
defZRMBank -loc U0_M0 -depth 33554432 -width 64 -ports 8 -full_loc U0_M0_F1
defZRMBank -loc U0_M0 -depth 33554432 -width 64 -ports 8 -full_loc U0_M0_F1
defZRMBank -loc U0_M0 -depth 33554432 -width 64 -ports 8 -full_loc U0_M0_F0
defZRMBank -loc U0_M0 -depth 33554432 -width 64 -ports 8 -full_loc U0_M0_F0
zrm_partitioning -algo min_port -perf_mode on -tgt_freq 10.000000 -mcp 2 -group_zrm_with_controllers off
