# Generated by zCoreBuild
#
# Set indivisible modules:
set_indivisible_module {ram_ZMEM_mem_base}
set_indivisible_module {rom_ZMEM_mem_base}
set_indivisible_module {ram_ZMEM_mem}
set_indivisible_module {rom_ZMEM_mem}

