################################################################################
#                                                                              #
# ZeBu (R) - Copyright (c) 2003 - 2017 by Synopsys, Inc                        #
# -------------------------------------------------------                      #
#                                                                              #
#   Design configuration script for zPar.                                      #
#   This file has been generated by zTopBuild.                                 #
#                                                                              #
################################################################################

System quiet
puts "Loading configuration for design top"
Design    new 	top
Design    set 	top.netlist            edif/top.edf.gz
Design    set 	top.top                top

puts "Design configuration for zPar from zCoreBuild, core: Part_0."
source work.Part_0/zPar_design_conf.tcl

