# EMULATION and VERIFICATION ENGINEERING (c) - 2003-2006
# ------------------------------------------------------
# zcore configuration script for zPar

System quiet
puts "Loading configuration for design top"
Core    set 	${CORENAME}.netlist 	${COREPATH}edif/top.edf.gz
Core    set 	${CORENAME}.top 	top
Module    new 	${CORENAME}|U0_M0
Core    set 	${CORENAME}.module  	0 ${CORENAME}|U0_M0
Module    set 	${CORENAME}|U0_M0.netlist 	${COREPATH}edif/U0_M0.edf.gz
Module    set 	${CORENAME}|U0_M0.top 	U0_M0
Component new 	U0_M0_F0
Component set 	U0_M0_F0.netlist 	${COREPATH}edif/U0_M0_F0.edf.gz
Component set 	U0_M0_F0.top 	U0_M0_F0
Component set 	U0_M0_F0.type 	XC7V2000
Component set 	U0_M0_F0.hierarchy 	U0_M0_F0.U0_M0_F0_core
Component set 	U0_M0_F0.zcei_capable 	false
if { [file exists /U0_M0_F0.zcf] } { 
Component set 	U0_M0_F0.constraintFile 	/U0_M0_F0.zcf 
}
Module    set 	${CORENAME}|U0_M0.component 	0 U0_M0_F0

# -----

puts "# no bufg propag for zceiClockPort clocks"; flush stdout
System nobufg
puts "# FK related routing directives"; flush stdout
puts "################################################################"; flush stdout
puts "# zPar STEP : Loading 1 UCF constraints       "; flush stdout
puts "################################################################"; flush stdout

# UCF constraints generated by zCoreBuild
# FPGA U0_M0_F0
Component set U0_M0_F0.ConstraintLine "#xdc_addconst delay
set_max_delay -datapath_only -from \[get_pins -hierarchical {*zMem_multiport_FROM_clk_50\*/Q}] -to \[get_cells -hierarchical {*zMem_multiport_TO_clk_50\*}] 40.0"
puts ""; flush stdout
puts ""; flush stdout
System quiet
