false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/u_check/sqnod_sqnet24} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_0_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_0_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_1_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_1_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_2_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_2_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_3_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_3_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_4_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_4_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_5_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_5_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_6_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_6_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_7_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_7_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_8_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_8_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_9_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_wr_9_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_0_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_0_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_1_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_1_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_2_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_2_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_3_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_3_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_4_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_4_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_5_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_5_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_6_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_6_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_7_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_7_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_8_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_8_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_9_/zebu_force_ins/mux\.lut_mux} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_stb/zforce_proba_rd_9_/zebu_force_ins/mux\.lut_mux} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_dut/u_fifo/u_fifo_usage_spy/zfast_39leio2bop9a2} {I0} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_dut/u_fifo/u0_clkg/sqnod_clkout} {I1} {O} -clock -data
false_timing_arc_on_instance {design/U0_M0_F0/U0_M0_F0_core/u_dut/u_check/sqnod_sqnet24} {I1} {O} -clock -data
